// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"10","screenWidth":"768","screenHeight":"672","changeWindowWidthTo":"768","changeWindowHeightTo":"672","renderingMode":"auto","alwaysDash":"off"}},
{"name":"DisableFastForward","status":true,"description":"イベント高速化禁止プラグイン","parameters":{}},
{"name":"BugFixWebPlayTest","status":true,"description":"Web実行のテストプレー防止プラグイン","parameters":{}},
{"name":"BugFixImageOnLoad","status":true,"description":"画像ロード遅延時のエラー修正プラグイン","parameters":{}},
{"name":"PictureVariableSetting","status":true,"description":"ピクチャ関連のイベント機能拡張プラグイン","parameters":{"初期値":"OFF","ピクチャ表示最大数":""}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"false"}},
{"name":"PictureSpriteSheet","status":true,"description":"ピクチャのスプライトシート化プラグイン","parameters":{}},
{"name":"ActorStepAnim","status":true,"description":"マップ上でパーティリーダー及びフォロワーに、\r\n足踏みのアニメーションを追加します。","parameters":{}},
{"name":"Gamefocus","status":true,"description":"ゲームがアクティブウィンドウでなくなった際に、\r\nオーディオかビデオ、もしくはその両方を一時停止します。","parameters":{"Pause Audio":"true","Pause Graphics":"true"}},
{"name":"SmartPath","status":true,"description":"イベントもしくはプレイヤーに、高度な経路探索を提供します。","parameters":{}},
{"name":"UCHU_MobileOperation","status":true,"description":"スマホ操作用プラグイン。横持ち/縦持ちに対応した仮想ボタン、\r\nタッチ操作の方法を追加拡張し、スマホプレイを快適にします。","parameters":{"---PC Option---":"","PC BtnDisplay":"false","PC TouchExtend":"false","---File Path---":"","DPad Image":"./img/system/DirPad.png","ActionBtn Image":"./img/system/ActionButton.png","CancelBtn Image":"./img/system/CancelButton.png","---Button Customize---":"","Button Opacity":"0.7","Vertical BtnZoom":"1.7","Tablet BtnZoom":"0.8","TabVertical BtnZoom":"1.1","HideButton OnMessage":"true","DPad Visible":"true","DPad Size":"200","DPad Margin":"10; 10","DPad Orientation":"left; bottom","DPad OpelationRange":"1.3","DPad DiagonalRange":"0.3","ActionBtn Visible":"true","ActionBtn Size":"100","ActionBtn Margin":"10; 90","ActionBtn Orientation":"right; bottom","CancelBtn Visible":"false","CancelBtn Size":"100","CancelBtn Margin":"110; 10","CancelBtn Orientation":"right; bottom","---TouchInput Extend---":"","Flick PageUp-PageDown":"false","HoldCanvas ActionBtn":"false","OutCanvas CancelBtn":"false","OutCanvas ActionBtn":"false","--!need AnalogMove.js!--":"","Analog Move":"false","Analog Sensitivity":"1.8"}},
{"name":"AutoLoad","status":true,"description":"タイトル画面仕様変更プラグイン","parameters":{"効果音演奏":"OFF","完全スキップ":"ON","タイトルマップID":"2"}}
];
